### ISSUE TITLE
SAP BTP kubectl Plugin does not work with mTLS credentials

### ISSUE THREAD

**Issue by patrickhuy** [SAP/sap-btp-service-operator#113]
Currently the kubectl plugin does not work when mTLS credentials are provided.

It would be nice to support that as well.

Remark: currently the plugin directly retrieves and uses the credentials used by the operator, this creates an intresting security model (=> users of the plugin need to be admins of the operator as well, operator operates cluster wide by default, users might only have access to specific namespaces) - maybe an alternative solution could be found where users talk to the operator instead

**Comment by pavelmaliy** [comment]
yes mTLS option not supported yet in the plugin,
This plugin is an experimental we weren't sure if it needed but if it's useful we'll add mTls option.

You right you must be powerful user that can read operator secret in order to use this plugin it aimed for unmanaged clusters for open-source community.
For managed clusters in SAP you can use cockpit, cpcli, smctl for marketplace, in the future we can consider broker CRD just like svcat and you can see the marketplace inside your cluster.
