### ISSUE TITLE
Question: How to integration btp service operator in umbrella helm chart

### ISSUE THREAD

**Issue by ricogu** [SAP/sap-btp-service-operator#129]
I tried to add **sap-btp-service-operator** as a subchart of a umbrella helm chart

The issue is that the cert-manager has to be preinstalled before we can install the operator and in umbrella helm chart we have no influence on which chart to be install before or after another chart

May I ask for you advice?

**Comment by rufreakde** [comment]
@ricogu I am not from the btp-service-operator team but just general points to this since I read your issue:
If you have full control over the kubernetes cluster try to look into some tools allowing for declarative deployments like [argoCD](https://argo-cd.readthedocs.io/en/stable/) this allows much more detailed control.

If you just need to provide your own reusable helmchart for others to use and that can be deployed anywhere. You can use
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/ to check if a subchart is installed and then after it is ready start the deployment of the other component.

Note that this is a workaround! And not suggested!
Usually a helm chart should not have dependencies on other components it is self contained. So I think the "the cert-manager" should be installed by the helmchart? Or should not be a dependency I am not sure what is wrong in your case. Seems like a Bug to me. I would raise this as a bug here for the experts.
