### ISSUE TITLE
Question: How to bind service instance existing in Cloud Foundry via service operator?

### ISSUE THREAD

**Issue by sssfire** [SAP/sap-btp-service-operator#136]
Hello,

Background: We have multiple applications deployed in BTP Cockpit in Cloud Foundry env. And they share and bind the same service instances such as xsuaa broker, audit log,  which are created in the same subaccount in Cloud Foundry. We have also some applications deployed in k8s env, which to reuse these service instances by coping service key of these instances to the environment, to remote access these services. Now we plan to use btp-service-operator to access the service instances

Question: After trying the btp service operator, we find that we cannot bind existing cloud foundry service instances in k8s env. And we also cannot bind the service instance in cloud foundry created by btp-service-operator. It seems that service instances in both env are isolated.  So my question is how to bind service instances that exist in cloud foundry via service operator? If not, is there any other official solution to access these service instances from k8s environment?  

Thanks a lot!

**Comment by pavelmaliy** [comment]
Hi,
It's not possible to mix instances and binding between other environments
There is a feature of instance sharing in service manager but service provider should allow it.

**Comment by sssfire** [comment]
I can get service instances that are only created by service operator via service manager API. Is it possible to get service instances created by cloud foundry via these apis?

**Comment by pavelmaliy** [comment]
You can see all services of your SA using service manager API but you can't perform actions on them, it's by design because the owner of the service is the platform CF/K8S.
If SM will allow to perform actions such as delete/update the platform won't be aware of it and it will cause inconsistencies.

BTW you need SA Admin plan to see all instances and not the one you provide to BTP Operator which indeed limited only to kubernetes.

**Comment by sssfire** [comment]
ok, got it. Thank you very much! :)
