### ISSUE TITLE
CRDs are not in the right folder

### ISSUE THREAD

**Issue by guymeron** [SAP/sap-btp-service-operator#147]
CRDs should be moved to `sapbtp-operator-charts/crds` folder.
See relevant documentation: https://helm.sh/docs/topics/charts/#the-chart-file-structure

**Comment by loewenstein** [comment]
I tend to disagree with the Helm documentation. One thing worth considering/keeping in mind after you moved the CRDs is that Helm will not update the CRD, ever.
If you plan iterating on the CRD, you will have to reconsider this move probably.

The old location is only marginally better, because if someone removes the Helm chart (potentially with the intent to reinstall) Helm would remove the CRD, which will cause removal of all CR instances of it, which will cause the service instances to be deleted... Data loss included.

**Comment by loewenstein** [comment]
You might want to check with the Helm community, but in the past the Helm maintainers where decidedly resistant to do any kind of update to CRDs. That was the case with the `deploy-crd` hook (or however that was called precisely) and it didn’t change with the introduction of the `crds` folder in Helm 3.0.

In the past we chose to have a separate chart for the CRD, so that a removal of our operator didn’t necessarily trigger the removal of all CRs. It’s a bit impractical from a chart lifecycle management point of view, because installing comprises to install two distinct charts then, but it was the solution that had the right balance.

**Comment by guymeron** [comment]
The advantage of this change is leaving CRD after chart uninstallation.
Currently, CRDs will be deleted upon `helm delete` command, this might cause data loss of service instances which might need to be retained from legal point of view e.g. audit log.
In cases of CRD upgrade, I think it should be a manual action which should be documented in the upgrade guide e.g. kube-prometheus-stack https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-33x-to-34x

**Comment by loewenstein** [comment]
I agree that CRDs in the `template/` directory introduce the risk for data loss.

However, I would avoid distinguishing installation from update as this is easy to miss. Hence, I'd go for a separate chart (or some other means of installing CRDs before the chart gets installed).

But that's of coure just my 2 cents.
