### ISSUE TITLE
"credentials-rotation" behaves not as expected / documented

### ISSUE THREAD

**Issue by levinanton** [SAP/sap-btp-service-operator#196]
We would like to better understand the expected behaviour of the https://github.com/SAP/sap-btp-service-operator#credentials-rotation feature and also raise some suspicious points.

### Original State

A `servicebinding` (for the IAS service) named `webshop-ias-binding` (with a `secret` resource having the same name):

```yaml
---
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: webshop-ias-binding
spec:
  serviceInstanceName: webshop-ias
  parameters:
    credential-type: X509_GENERATED
```

>Important to note it's binding ID is `e51faf51-0120-4e91-b81d-48ccb8836fdc` and status:
>
>```yaml
> Status:
>   Binding ID:  e51faf51-0120-4e91-b81d-48ccb8836fdc
>   Conditions:
>     Last Transition Time:  2022-08-08T07:01:34Z
>     Message:               ServiceBinding provisioned successfully
>     Observed Generation:   1
>     Reason:                Created
>     Status:                True
>     Type:                  Succeeded
>     Last Transition Time:  2022-08-08T07:01:34Z
>     Message:               
>     Reason:                Provisioned
>     Status:                True
>     Type:                  Ready
>   Instance ID:             cd2f4069-f4d7-4e95-b222-292fd893cee9
>   Observed Generation:     1
>   Ready:                   True
>```

### Apply "credentials-rotation"

`webshop-ias-binding` binding changed to:

```yaml
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: webshop-ias-binding
spec:
  serviceInstanceName: webshop-ias
  parameters:
    credential-type: X509_GENERATED
  credentialsRotationPolicy:
    enabled: true
    rotationFrequency: '5m'
    rotatedBindingTTL: '1m'
```

>Rotation frequency is 5 minutes. Rotated binding should be kept for 1 minute.

### Current State

- New `servicebinding` created (respective `secret` resource created as well):

  ```
  webshop-ias-binding               webshop-ias             Created   True    2d22h
  webshop-ias-binding-cqf1ho        webshop-ias             Updated   True    36s
  ```

  ```
  webshop-ias-binding               Opaque                                15     2d22h
  webshop-ias-binding-cqf1ho        Opaque                                15     3m16s
  ```

Now some unclear / suspicious points:

1. Original binding `webshop-ias-binding` got a new ID now `3df009af-e15e-450b-8eaf-f67e66bc6849`

  >```yaml
  > Status:
  >   Binding ID:  3df009af-e15e-450b-8eaf-f67e66bc6849
  >   Conditions:
  >     Last Transition Time:          2022-08-11T05:45:52Z
  >     Message:                       ServiceBinding provisioned successfully
  >     Observed Generation:           2
  >     Reason:                        Created
  >     Status:                        True
  >     Type:                          Succeeded
  >     Last Transition Time:          2022-08-11T05:45:52Z
  >     Message:                       
  >     Reason:                        Provisioned
  >     Status:                        True
  >     Type:                          Ready
  >   Instance ID:                     cd2f4069-f4d7-4e95-b222-292fd893cee9
  >   Last Credentials Rotation Time:  2022-08-11T05:45:52Z
  >   Observed Generation:             2
  >   Ready:                           True
  >```

  and it previous ID `e51faf51-0120-4e91-b81d-48ccb8836fdc` is now assigned to `webshop-ias-binding-cqf1ho`:

  >```yaml
  > Status:
  >   Binding ID:  e51faf51-0120-4e91-b81d-48ccb8836fdc
  >   Conditions:
  >     Last Transition Time:  2022-08-11T05:45:42Z
  >     Message:               ServiceBinding updated successfully
  >     Observed Generation:   1
  >     Reason:                Updated
  >     Status:                True
  >     Type:                  Succeeded
  >     Last Transition Time:  2022-08-11T05:45:42Z
  >     Message:               
  >     Reason:                Provisioned
  >     Status:                True
  >     Type:                  Ready
  >   Instance ID:             cd2f4069-f4d7-4e95-b222-292fd893cee9
  >   Observed Generation:     1
  >   Ready:                   True
  > Events:
  >   Type    Reason         Age   From            Message
  >   ----    ------         ----  ----            -------
  >   Normal  SecretCreated  44m   ServiceBinding  SecretCreated
  >```

  **Question:** is it expected (that "temporary" binding overtakes the id of the original one)?

2. Original `webshop-ias-binding` has `Last Credentials Rotation Time` but in spite of the configured 5 minutes frequency, it has been rotated only once.

3.  `rotatedBindingTTL ` is set to 1 minute, so we have expected that this "temporary" `webshop-ias-binding-cqf1ho` will be deleted but it didn't happen.

4. We have also expected that the `secret` resource of the original binding `webshop-ias-binding` will be updated but it didn't happen either.

  ```
  webshop-ias-binding               Opaque                                15     2d23h
  webshop-ias-binding-cqf1ho        Opaque                                15     52m
  ```

----

Could you please take a look at those suspicious points (from our perspective) and shed some lights on the expected behaviour? Maybe there are more materials we could read about this feature to better understand how it is supposed to work?

Thanks in advance!

**Comment by uwe-klinger** [comment]
Hi @levinanton,

I've observed the same behavior and I think it is a bug: The reconciler isn't called regularly.

Accidentially it works if both values <=1s it. I guess that's because each change triggers a new reconcile run which has a delay of ~1s. But it seems as there is no regular run, so the code that checks for rotation and deletion of old credentials is not triggered.

It works only if the reconciler is triggered by a change manually, e.g.:

- If you just edit `webshop-ias-binding` it will rotate the credential.
- If you edit `webshop-ias-binding-cqf1ho` after its expired, it will be deleted

e.g.: `kubectl edit servicebinding webshop-ias-binding` → add a label in vi

You can see that the implementation of the reconciler is correct, because it then rotates or deletes the servicebinding. But it's simply not called.

Can you please change the description to indicate that this is a bug, so that the folks can pick it up.
 
Thanks!

**Comment by levinanton** [comment]
Thanks @uwe-klinger for your detailed comment. 

We are on Gardener-managed K8s cluster and use manually installed SAP BTP Service Operator of `v0.2.7`

@ Service Operator colleagues: I am changing the title to indicate that there is a bug / unexpected behaviour (confirmed by one more colleague).

**Comment by kerenlahav** [comment]
Hi,
There are two behaviors described in the comments:
1. rotation timing
2. rotation behavior

'rotationFrequency' and 'rotatedBindingTTL' is the **minimum** time for the frequency and TTL, as described in the README the credentialsRotationPolicy is evaluated and executed during control loop which runs on every update or during full reconciliation process, where full reconciliation process is every 10 hours.
There is an option to force rotation by adding an annotation to the binding - services.cloud.sap.com/forceRotate

Regarding the rotation behavior, the behavior described by @levinanton is the expected behavior, the original binding and secret will always contain the newest credentials, and the newly created binding and secret are used to keep the previous credentials until the configured TTL is passed. 
If the operator would create a new binding and would not update the original one, you would have to update your applications to refer to the new binding each time a rotation occurs, the current behavior makes the rotation transparent to the application.

Thanks
