### ISSUE TITLE
Service instance with "DELETE FAILED" status can not provision any service binding

### ISSUE THREAD

**Issue by alperdedeoglu** [SAP/sap-btp-service-operator#249]
When a service instance have a status **DELETE FAILED**, service binding of that service instance can not be provisioned anymore with status **NOT PROVISIONED**.  Therefore this status is preventing any interaction with the service instance from the runtime its provisioned.

Expected Behavior: A service with **DELETE FAILED** status should still be able to provision service binding since it can not be deleted.

**Comment by kerenlahav** [comment]
It is not possible by design to create a binding to an instance that is being deleted.
check out the solution to such case in the troubleshooting section
https://github.com/SAP/sap-btp-service-operator#troubleshooting-and-support

**Comment by alperdedeoglu** [comment]
Hi @kerenlahav,

If instance is being deleted (deletion is ongoing), I agree that binding can not be created. 
But if the instance is already can not be deleted and still there, this is totally different situation.
I think most of the service brokers on SAP BTP are allowing to create bindings even if they are in DELETE_FAILED status.
At least that is my experience on CF. 

IMHO, we need to differentiate between "BEING_DELETED" and "DELETE_FAILED" statuses since they have different behaviours in service broker side.

Why do you think that it is not possible by design?

BR,

Alper

**Comment by kerenlahav** [comment]
The behavior in CF and in k8s is different since the two platforms behave differently.
Unlike CF, once you requested to delete a resource in k8s, it cannot be undone, the corresponding operator will keep continuing deleting it until it succeeds, it means that in k8s once "delete" was requested the state is always "BEING_DELETED" (even when it failed).
Take for example "namespace" resource, once you requested to delete a namespace it will not be deleted until all resources in it are removed, if you try to create a new resource in it you will fail because the namespace is in the deletion process (even though it cannot be deleted), same with instances and bindings
