### ISSUE TITLE
Prevent deletion for protected service instance

### ISSUE THREAD

**Issue by MarioSchle** [SAP/sap-btp-service-operator#292]
Hi,

we want to prevent an accidental service instance deletion triggered by the customer. Therefore we introduced a parameter called "protected". In case this parameter is set to true the operator should not trigger a deletion and return an error message instead. This error message would guide the customer how to set the "protected" parameter to false in case he really wants to delete the service instance.
Does the operator support such kind of behavior or is there a possibility to prevent service instance deletions in case certain parameters are set?

**Comment by kerenlahav** [comment]
Hi,
Once a resource is marked for deletion in k8s there is no way back, in case of failure the operator will continue to trigger a delete request until it succeeds. what you're asking should be done in a webhook to block the deletion request, but there is no way for the operator to check if the deletion is allowed or not since there are no rest requests within the webhook.

**Comment by avilupu** [comment]
Hi @MarioSchle 
We have introduced a new feature that allows service developers to mark instances that should be protected from accidental or unauthorized deletion. This feature ensures there is no data loss or critical configuration issues.

See [Prevent Instance Deletion](https://github.com/SAP/sap-btp-service-operator/blob/main/README.md#anotations) 

Available from release [v0.5.1](https://github.com/SAP/sap-btp-service-operator/releases/tag/v0.5.1)
