### ISSUE TITLE
Race condition: unable to remove service instances due to dangling temp service binding

### ISSUE THREAD

**Issue by ptesny** [SAP/sap-btp-service-operator#449]
Race condition: unable to remove service instances due to dangling temp service binding

Deploy any BTP service with credential rotation using helm/argocd. 
Make sure both temp and service bindings are present. (==the rotation took place)
Observe the temp binding is unmanaged. (== no helm/argocd label/annotation)
Try to undeploy the service (with helm/argocd).... this will result in having a ghost service instance on the BTP subaccount side due the dangling temp binding

**Comment by I065450** [comment]
Hi @ptesny 

I have tested this, and the issue was not reproduced. I removed the cluster using Helm when there was a binding, and after rotating the binding, everything was removed from BTP as expected.
<img width="309" alt="Screenshot 2024-07-11 at 15 52 04" src="https://github.com/SAP/sap-btp-service-operator/assets/52195888/b81a282f-7c09-40f5-ac48-374f80ec7f5b">


Our pre-delete script can be found here: [pre-delete-job.yml](https://github.com/SAP/sap-btp-service-operator/blob/main/sapbtp-operator-charts/templates/pre-delete-job.yml). It brings all bindings and instances without label/annotation queries.

Best Regard,
Naama

**Comment by ptesny** [comment]
@I065450 Thank you for taking the effort to try to reproduce it.  All I can say it happened to me at least once with ArgoCD but this must be very rare. 
ArgoCD will template the helm charts and then will use kubectl on the server side to deploy the manifest. This is not the same using helm to deploy/undeploy a chart.

**Comment by I065450** [comment]
Hi @ptesny 
After investigating, it appears that ArgoCD does not support the Helm hook pre-delete as mentioned in their documentation: [ArgoCD Helm Support](https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/helm.md).
You can write your own script to ensure all instances and bindings are deleted before the operator is removed. 
Alternatively, you could request a fix from ArgoCD, as there is already an open issue on this topic: [ArgoCD Issue #13975](https://github.com/argoproj/argo-cd/issues/13975).

Best Regards,
Naama
