### ISSUE TITLE
ServiceBinding Secret output format

### ISSUE THREAD

**Issue by jkbschmid** [SAP/sap-btp-service-operator#61]
Hi there,

I have a golang application that consumes multiple BTP, runs on CF and which I would like to deploy to K8s as well.
To read in all the binding credentials I have structs that I unmarshal into from VCAP_SERVICES, something like
```
type myService struct{
  key1 string
  key2 otherType
}
var x myServices
.. json.Unmarshal(.., &x) ...
```

The way the service operator creates K8s secrets makes it hard to populate structs with service credentials.
It's possible to use either 
*  env variables, where I have to assign each env variable to the correct struct field 
* files, where one file per credential key is created. It's possible to create a map with one key per file, unmarshal the file content, marshal to string, unmarshal to struct. This is doable but somewhat cumbersome.

Therefore my question(s): 
What is the recommended way to unmarshal service credentials into golang structs?
Is there perhaps a library that you use (internally)? Have you already thought about creating secrets that contain one key only so unmarshaling is simplified?

Thanks and best regards!

**Comment by pavelmaliy** [comment]
Hi,
Secrets are standard way of storing sensitive data in kubernetes and we put there binding result exactly as we get it from brokers, same behavior you can see in SVCAT.
I am not sure what's your exact questions but secret's data is treated as standard map[string][]byte  in golang app.
Each service returns different structure in its binding response so its impossible to get dedicated struct for all bindings.

**Comment by phil9909** [comment]
> we put there binding result exactly as we get it from brokers,

I would say you don't store it "exactly" as you get it :smile: You first process it in this `serialize` method before storing it:

https://github.com/SAP/sap-btp-service-operator/blob/91943850d30cda4ab4fda76eba3ba5cdfb017216/controllers/controller_util.go#L43-L55

Unfortunately, that process is irreversible, as you can't destiguish between the number `42` and the string `"42"`, the array `[1, 2, 3]` and the string `"[1, 2, 3]"`, etc.

It would be really nice, if you would just store the credentials in one key, serialized as a json (for compatibility this probably needs to be configurable). That way one could easily unmarshal into a go struct.

Let me give an example.
So instead of creating a secret like this:

```yaml
apiVersion: v1
kind: Secret
stringData:
    key1: value1
    key2: value2
```

You would create one looking like this:

```yaml
apiVersion: v1
kind: Secret
stringData:
    credentials: '{"key1": "value1", "key2": "value2"}'
```

This would be much easier to work with for our team.
@jkbschmid I guess that would also solve your problem, right?
@pavelmaliy I can create a PR for this, if you wish.


See similar issue in SVCAT: https://github.com/kubernetes-sigs/service-catalog/issues/1109
and my proposal to fix it: https://github.com/kubernetes-sigs/service-catalog/pull/2886
I don't think this will be ever fixed over there, as the project seems dead.

**Comment by pavelmaliy** [comment]
**@phil9909** Thanks for the clarification, I saw your proposal for fix we can do something like that here as well.
Go ahead you can create PR we'll review it.

**@jkbschmid**  I understand your use case as well, applications that run on CF will have much smoother transition to K8S if the binding secret will be similar to VCAP_SERVICES.

**Comment by loewenstein** [comment]
@phil9909 could we make this as an additive change, i.e. serialize the full json while still populating separate secret keys with single values?

**Comment by phil9909** [comment]
I talked with @loewenstein via phone to understand his use-case:
We agreed that it is unlikely that an application will need both at the same time. But it could happen that an update of an application switches from one to the other.
This is still possible by creating a new binding for the new version of the application.

**Comment by pavelmaliy** [comment]
you can upgrade to v0.1.10 version with the latest commit
