### ISSUE TITLE
Support for limiting watched namespaces

### ISSUE THREAD

**Issue by patrickhuy** [SAP/sap-btp-service-operator#67]
It would be useful to have the functionality that BtpServiceOperator could only act on resources in certain namespaces or with a certain label attached to them. That way multiple ServiceOperators, each attached to different BTP accounts could be installed in the same Kubernetes cluster.

**Comment by pavelmaliy** [comment]
hi,
we have something that may solve this problem there is a possibility in which BtpServiceOperator will use the secret in the namespace of the ServiceInstance/ServiceBinding in order to communicate with SM, otherwise it has fallback to cluster secret.
[see resolver](https://github.com/SAP/sap-btp-service-operator/blob/main/internal/secrets/resolver.go#L33) you will have one ServiceOperator that access SM with different accounts according to secrets in the namespace.

I am not sure that there is a support in helm parameters for it yet, will this work for you?

**Comment by patrickhuy** [comment]
Yes that sounds very good and covers my use case!

Also exposing it for the helm chart would be greatly appreciated.

**Comment by pavelmaliy** [comment]
actually after rechecking, it enabled by default so you can use this feature right away.
https://github.com/SAP/sap-btp-service-operator/blob/main/internal/config/config.go#L30

**Comment by patrickhuy** [comment]
@pavelmaliy so what I need to do is create a secret called `sap-btp-service-operator` in the consuming namespaces?

**Comment by pavelmaliy** [comment]
Exactly, with your binding credentials of SAP Service Manager service (technical name: service-manager) with the plan: service-operator-access
