### ISSUE TITLE
management namespace is not searched

### ISSUE THREAD

**Issue by techaware** [SAP/sap-btp-service-operator#75]
https://github.com/SAP/sap-btp-service-operator/blob/a3292fe5620f6509f58de7c599fe8b53a3dc91c8/internal/secrets/resolver.go#L46

If secret is not found in the resource namespace then it should be searched in management namespace. However, the code still searched in the resource namespace (as per the written code). 
I think it needs a fix.

**Comment by pavelmaliy** [comment]
it actually by design,
There are 3 levels let's say the resource namespace is 'mynamespace'
First: Operator tries to find the 'sap-btp-service-operator' secret in the same namespace as the resource - 'mynamespace'
Second: Operator tries to find the secret in managed namespace with namespace prefix 'mynamespace-sap-btp-service-operator'
Third: Operator tries to find central cluster secret 'sap-btp-service-operator' in managed namespace


The option you mentioned is when you want central namespace to manage all tenants rather than distribute secrets a cross namespaces

**Comment by techaware** [comment]
Thank you! Now I understand the flow better.
It would be good idea to change the log for second scenario 
from:
sr.Log.Info("Searching for namespace secret in management namespace", "namespace", namespace, "managementNamespace", sr.ManagementNamespace, "name", name)
to: 
sr.Log.Info("Searching for namespace secret in management namespace", "managementNamespace", sr.ManagementNamespace, "name", fmt.Sprintf("%s-%s", namespace, name))
